modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="ahjinmod" #mandatory
version="0.0.1" #mandatory
displayName="Ahjin Mod" #mandatory
description='''
Solo leveling based mod.
'''